<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $roses = Category::where('slug', 'roses')->first();
        $bouquets = Category::where('slug', 'bouquets')->first();
        $occasions = Category::where('slug', 'occasions')->first();
        $plants = Category::where('slug', 'plants')->first();
        $luxury = Category::where('slug', 'luxury')->first();
        $gifts = Category::where('slug', 'gifts')->first();

        $products = [
            // ─── Roses ───────────────────────────────────
            [
                'category_id' => $roses->id,
                'name_en' => 'Red Rose Bunch',
                'name_ar' => 'باقة ورد أحمر',
                'description_en' => 'A stunning bunch of 20 premium red roses, perfect for expressing love and passion.',
                'description_ar' => 'باقة مذهلة من 20 وردة حمراء فاخرة، مثالية للتعبير عن الحب والعاطفة.',
                'slug' => 'red-rose-bunch',
                'price' => 8.500,
                'sale_price' => 6.500,
                'image' => 'products/red-rose-bunch.jpg',
                'images' => ['products/red-rose-bunch-2.jpg', 'products/red-rose-bunch-3.jpg'],
                'sku' => 'RS-001',
                'stock' => 50,
                'rating' => 4.5,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $roses->id,
                'name_en' => 'Pink Rose Arrangement',
                'name_ar' => 'ترتيب ورد وردي',
                'description_en' => 'Elegant pink roses beautifully arranged in a glass vase, ideal for celebrations.',
                'description_ar' => 'ورود وردية أنيقة مرتبة بشكل جميل في مزهرية زجاجية، مثالية للاحتفالات.',
                'slug' => 'pink-rose-arrangement',
                'price' => 12.000,
                'sale_price' => null,
                'image' => 'products/pink-rose-arrangement.jpg',
                'images' => ['products/pink-rose-arrangement-2.jpg'],
                'sku' => 'RS-002',
                'stock' => 30,
                'rating' => 4.2,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $roses->id,
                'name_en' => 'White Rose Box',
                'name_ar' => 'صندوق ورد أبيض',
                'description_en' => 'Luxurious white roses in a premium gift box, symbolizing purity and elegance.',
                'description_ar' => 'ورود بيضاء فاخرة في صندوق هدايا راقٍ، ترمز للنقاء والأناقة.',
                'slug' => 'white-rose-box',
                'price' => 15.000,
                'sale_price' => 12.500,
                'image' => 'products/white-rose-box.jpg',
                'images' => ['products/white-rose-box-2.jpg', 'products/white-rose-box-3.jpg'],
                'sku' => 'RS-003',
                'stock' => 20,
                'rating' => 4.8,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ─── Bouquets ────────────────────────────────
            [
                'category_id' => $bouquets->id,
                'name_en' => 'Sunshine Bouquet',
                'name_ar' => 'باقة أشعة الشمس',
                'description_en' => 'Bright yellow and orange flowers mixed to bring warmth and joy to any space.',
                'description_ar' => 'زهور صفراء وبرتقالية زاهية ممزوجة لتجلب الدفء والبهجة لأي مكان.',
                'slug' => 'sunshine-bouquet',
                'price' => 10.000,
                'sale_price' => null,
                'image' => 'products/sunshine-bouquet.jpg',
                'images' => ['products/sunshine-bouquet-2.jpg'],
                'sku' => 'BQ-001',
                'stock' => 40,
                'rating' => 4.3,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $bouquets->id,
                'name_en' => 'Pastel Dream Bouquet',
                'name_ar' => 'باقة حلم الباستيل',
                'description_en' => 'Soft pastel-toned flowers creating a dreamy, romantic arrangement for special moments.',
                'description_ar' => 'زهور بدرجات الباستيل الناعمة تخلق ترتيباً حالماً ورومانسياً للمناسبات الخاصة.',
                'slug' => 'pastel-dream-bouquet',
                'price' => 14.000,
                'sale_price' => 11.000,
                'image' => 'products/pastel-dream-bouquet.jpg',
                'images' => ['products/pastel-dream-bouquet-2.jpg'],
                'sku' => 'BQ-002',
                'stock' => 25,
                'rating' => 4.6,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $bouquets->id,
                'name_en' => 'Wildflower Mix',
                'name_ar' => 'مزيج زهور برية',
                'description_en' => 'A carefree mix of wild-style flowers for a natural, rustic charm.',
                'description_ar' => 'مزيج عفوي من الزهور البرية لسحر طبيعي ريفي.',
                'slug' => 'wildflower-mix',
                'price' => 7.500,
                'sale_price' => null,
                'image' => 'products/wildflower-mix.jpg',
                'images' => [],
                'sku' => 'BQ-003',
                'stock' => 35,
                'rating' => 4.0,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ─── Occasions ───────────────────────────────
            [
                'category_id' => $occasions->id,
                'name_en' => 'Birthday Celebration Set',
                'name_ar' => 'طقم احتفال عيد ميلاد',
                'description_en' => 'Colorful flower arrangement with a birthday balloon, perfect for birthday surprises.',
                'description_ar' => 'ترتيب زهور ملون مع بالون عيد ميلاد، مثالي لمفاجآت أعياد الميلاد.',
                'slug' => 'birthday-celebration-set',
                'price' => 13.000,
                'sale_price' => null,
                'image' => 'products/birthday-set.jpg',
                'images' => ['products/birthday-set-2.jpg'],
                'sku' => 'OC-001',
                'stock' => 45,
                'rating' => 4.4,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $occasions->id,
                'name_en' => 'Wedding White Collection',
                'name_ar' => 'مجموعة العرس الأبيض',
                'description_en' => 'Elegant all-white floral collection designed for wedding ceremonies and receptions.',
                'description_ar' => 'مجموعة زهور بيضاء أنيقة مصممة لحفلات الزفاف والاستقبالات.',
                'slug' => 'wedding-white-collection',
                'price' => 35.000,
                'sale_price' => null,
                'image' => 'products/wedding-white.jpg',
                'images' => ['products/wedding-white-2.jpg', 'products/wedding-white-3.jpg'],
                'sku' => 'OC-002',
                'stock' => 10,
                'rating' => 4.9,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $occasions->id,
                'name_en' => 'Congratulations Bundle',
                'name_ar' => 'حزمة تهنئة',
                'description_en' => 'Celebrate achievements with this vibrant congratulatory flower bundle.',
                'description_ar' => 'احتفل بالإنجازات مع حزمة الزهور التهنئة المبهجة هذه.',
                'slug' => 'congratulations-bundle',
                'price' => 11.000,
                'sale_price' => 9.000,
                'image' => 'products/congrats-bundle.jpg',
                'images' => [],
                'sku' => 'OC-003',
                'stock' => 30,
                'rating' => 4.1,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],

            // ─── Plants ──────────────────────────────────
            [
                'category_id' => $plants->id,
                'name_en' => 'Orchid in Pot',
                'name_ar' => 'أوركيدا في أصيص',
                'description_en' => 'A beautiful potted orchid that lasts for weeks, bringing natural beauty indoors.',
                'description_ar' => 'أوركيدا جميلة في أصيص تدوم لأسابيع، تجلب الجمال الطبيعي للداخل.',
                'slug' => 'orchid-in-pot',
                'price' => 18.000,
                'sale_price' => null,
                'image' => 'products/orchid-pot.jpg',
                'images' => ['products/orchid-pot-2.jpg'],
                'sku' => 'PL-001',
                'stock' => 15,
                'rating' => 4.7,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $plants->id,
                'name_en' => 'Succulent Garden',
                'name_ar' => 'حديقة نباتات صحراوية',
                'description_en' => 'A mini garden of assorted succulents in a decorative planter, low maintenance.',
                'description_ar' => 'حديقة مصغرة من نباتات صحراوية متنوعة في أصيص زخرفي، سهلة العناية.',
                'slug' => 'succulent-garden',
                'price' => 9.000,
                'sale_price' => 7.500,
                'image' => 'products/succulent-garden.jpg',
                'images' => [],
                'sku' => 'PL-002',
                'stock' => 25,
                'rating' => 4.3,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],

            // ─── Luxury ──────────────────────────────────
            [
                'category_id' => $luxury->id,
                'name_en' => '100 Red Roses Basket',
                'name_ar' => 'سلة 100 وردة حمراء',
                'description_en' => 'A grand basket of 100 premium long-stemmed red roses for the ultimate statement.',
                'description_ar' => 'سلة فاخرة من 100 وردة حمراء طويلة الساق للبيان الأقصى.',
                'slug' => '100-red-roses-basket',
                'price' => 55.000,
                'sale_price' => null,
                'image' => 'products/100-red-roses.jpg',
                'images' => ['products/100-red-roses-2.jpg'],
                'sku' => 'LX-001',
                'stock' => 5,
                'rating' => 5.0,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $luxury->id,
                'name_en' => 'Golden Rose Box',
                'name_ar' => 'صندوق الورد الذهبي',
                'description_en' => 'Premium roses in a luxurious golden gift box, the height of sophistication.',
                'description_ar' => 'ورود فاخرة في صندوق هدايا ذهبي فخم، قمة الرقي.',
                'slug' => 'golden-rose-box',
                'price' => 42.000,
                'sale_price' => 38.000,
                'image' => 'products/golden-rose-box.jpg',
                'images' => ['products/golden-rose-box-2.jpg'],
                'sku' => 'LX-002',
                'stock' => 8,
                'rating' => 4.8,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],

            // ─── Gifts ───────────────────────────────────
            [
                'category_id' => $gifts->id,
                'name_en' => 'Flower & Chocolate Combo',
                'name_ar' => 'مزيج الزهور والشوكولاتة',
                'description_en' => 'A delightful combination of fresh flowers and premium Belgian chocolates.',
                'description_ar' => 'مزيج رائع من الزهور الطازجة وشوكولاتة بلجيكية فاخرة.',
                'slug' => 'flower-chocolate-combo',
                'price' => 16.000,
                'sale_price' => null,
                'image' => 'products/flower-chocolate.jpg',
                'images' => ['products/flower-chocolate-2.jpg'],
                'sku' => 'GF-001',
                'stock' => 20,
                'rating' => 4.5,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $gifts->id,
                'name_en' => 'Teddy Bear with Flowers',
                'name_ar' => 'دب محشو مع زهور',
                'description_en' => 'An adorable teddy bear paired with a cute flower arrangement for kids and loved ones.',
                'description_ar' => 'دب محشو لطيف مقترن بترتيب زهور جميل للأطفال والأحباء.',
                'slug' => 'teddy-bear-with-flowers',
                'price' => 13.500,
                'sale_price' => 11.000,
                'image' => 'products/teddy-flowers.jpg',
                'images' => [],
                'sku' => 'GF-002',
                'stock' => 30,
                'rating' => 4.2,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
