<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $eid = Category::where('slug', 'eid')->first();
        $weddings = Category::where('slug', 'weddings')->first();
        $birthday = Category::where('slug', 'birthday')->first();
        $anniversary = Category::where('slug', 'anniversary')->first();
        $graduation = Category::where('slug', 'graduation')->first();
        $mothersDay = Category::where('slug', 'mothers-day')->first();
        $loveRomance = Category::where('slug', 'love-romance')->first();
        $sympathy = Category::where('slug', 'sympathy')->first();

        $products = [
            // ═══════════════════════════════════════════════════════
            // 01 — EID
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $eid->id,
                'name_en' => 'Moonlit Saffron Bloom',
                'name_ar' => 'إزهار الزعفران القمري',
                'description_en' => 'A graceful bouquet inspired by peaceful Eid evenings, combining purity, warmth, and elegance in one luxurious arrangement. White Lilies with Golden Roses and Eucalyptus.',
                'description_ar' => 'باقة رائعة مستوحاة من أمسيات العيد الهادئة، تجمع بين النقاء والدفء والأناقة في ترتيب فاخر واحد. زنابق بيضاء مع ورد ذهبي وأوكالبتوس.',
                'slug' => 'moonlit-saffron-bloom',
                'price' => 26.000,
                'sale_price' => null,
                'image' => 'products/eid/moonlit-saffron-bloom.jpg',
                'images' => ['products/eid/moonlit-saffron-bloom-2.jpg'],
                'sku' => 'EID-001',
                'stock' => 30,
                'rating' => 4.5,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $eid->id,
                'name_en' => 'Crescent Velvet Garden',
                'name_ar' => 'حديقة المخمل الهلالية',
                'description_en' => 'A rich and velvety arrangement that brings a sophisticated festive atmosphere to Eid celebrations. Burgundy Carnations with Cream Tulips and Pampas Grass.',
                'description_ar' => 'ترتيب غني ومخملي يجلب أجواء احتفالية راقية لاحتفالات العيد. قرنفل بورغندي مع تول كريمي وعشب بامباس.',
                'slug' => 'crescent-velvet-garden',
                'price' => 24.000,
                'sale_price' => null,
                'image' => 'products/eid/crescent-velvet-garden.jpg',
                'images' => [],
                'sku' => 'EID-002',
                'stock' => 25,
                'rating' => 4.3,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $eid->id,
                'name_en' => 'Noor Al Zahra Basket',
                'name_ar' => 'سلة نور الزهراء',
                'description_en' => 'A radiant floral basket designed to symbolize joy, gratitude, and prosperity during the Eid season. Sunflowers, White Orchids, and Peach Roses.',
                'description_ar' => 'سلة زهور مشعة مصممة لترمز للفرح والامتنان والرخاء في موسم العيد. زهرة الشمس مع أوركيد أبيض وورد خوخي.',
                'slug' => 'noor-al-zahra-basket',
                'price' => 29.000,
                'sale_price' => null,
                'image' => 'products/eid/noor-al-zahra-basket.jpg',
                'images' => ['products/eid/noor-al-zahra-basket-2.jpg'],
                'sku' => 'EID-003',
                'stock' => 20,
                'rating' => 4.7,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $eid->id,
                'name_en' => 'Golden Lantern Petals',
                'name_ar' => 'بتلات الفانوس الذهبي',
                'description_en' => 'Inspired by glowing lanterns during Eid nights, this bouquet delivers warmth and cheerful energy. Yellow Chrysanthemums with Ivory Roses.',
                'description_ar' => 'مستوحاة من الفوانيس المضيئة في ليالي العيد، هذه الباقة تنشر الدفء والطاقة المرحة. أقحوان أصفر مع ورد عاجي.',
                'slug' => 'golden-lantern-petals',
                'price' => 22.000,
                'sale_price' => 18.500,
                'image' => 'products/eid/golden-lantern-petals.jpg',
                'images' => [],
                'sku' => 'EID-004',
                'stock' => 35,
                'rating' => 4.2,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $eid->id,
                'name_en' => 'Desert Pearl Ensemble',
                'name_ar' => 'مجموعة لؤلؤة الصحراء',
                'description_en' => 'A premium arrangement with a soft luxurious aesthetic inspired by timeless Arabian elegance. White Hydrangeas with Champagne Roses and Silver Foliage.',
                'description_ar' => 'ترتيب فاخر بجمالية ناعمة وفاخرة مستوحاة من الأناقة العربية الخالدة. هيدرانجيا بيضاء مع ورد شمبانيا وأوراق فضية.',
                'slug' => 'desert-pearl-ensemble',
                'price' => 33.000,
                'sale_price' => null,
                'image' => 'products/eid/desert-pearl-ensemble.jpg',
                'images' => ['products/eid/desert-pearl-ensemble-2.jpg'],
                'sku' => 'EID-005',
                'stock' => 10,
                'rating' => 4.9,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 02 — WEDDINGS
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $weddings->id,
                'name_en' => 'Ivory Vow Symphony',
                'name_ar' => 'سيمفونية العهد العاجي',
                'description_en' => 'A timeless bouquet crafted to reflect purity, commitment, and everlasting love. White Roses, Peonies, and Baby\'s Breath.',
                'description_ar' => 'باقة خالدة مصممة لتعكس النقاء والالتزام والحب الأبدي. ورد أبيض مع بيونيات وأنفاس الطفل.',
                'slug' => 'ivory-vow-symphony',
                'price' => 42.000,
                'sale_price' => null,
                'image' => 'products/weddings/ivory-vow-symphony.jpg',
                'images' => ['products/weddings/ivory-vow-symphony-2.jpg'],
                'sku' => 'WED-001',
                'stock' => 15,
                'rating' => 4.8,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $weddings->id,
                'name_en' => 'Forever Silk Garden',
                'name_ar' => 'حديقة الحرير الأبدية',
                'description_en' => 'A soft and elegant arrangement designed to celebrate gentle romance and new beginnings. Blush Tulips with Cream Carnations.',
                'description_ar' => 'ترتيب ناعم وأنيق مصمم للاحتفال بالرومانسية الرقيقة والبدايات الجديدة. تول وردي مع قرنفل كريمي.',
                'slug' => 'forever-silk-garden',
                'price' => 39.000,
                'sale_price' => null,
                'image' => 'products/weddings/forever-silk-garden.jpg',
                'images' => [],
                'sku' => 'WED-002',
                'stock' => 20,
                'rating' => 4.6,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $weddings->id,
                'name_en' => 'Velvet Chapel Bloom',
                'name_ar' => 'إزهار الكنيسة المخملي',
                'description_en' => 'A dramatic floral arrangement that captures passion and luxury in every detail. Red Roses with Cascading White Orchids.',
                'description_ar' => 'ترتيب زهور درامي يلتقط الشغف والفخامة في كل تفصيل. ورد أحمر مع أوركيد أبيض متدلي.',
                'slug' => 'velvet-chapel-bloom',
                'price' => 48.000,
                'sale_price' => null,
                'image' => 'products/weddings/velvet-chapel-bloom.jpg',
                'images' => ['products/weddings/velvet-chapel-bloom-2.jpg', 'products/weddings/velvet-chapel-bloom-3.jpg'],
                'sku' => 'WED-003',
                'stock' => 8,
                'rating' => 4.9,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $weddings->id,
                'name_en' => 'Celestial Promise Bouquet',
                'name_ar' => 'باقة الوعد السماوي',
                'description_en' => 'A dreamy bouquet with soft tones symbolizing loyalty, serenity, and eternal promises. White Hydrangeas with Lavender Roses.',
                'description_ar' => 'باقة حالمة بدرجات ناعمة ترمز للولاء والهدوء والوعود الأبدية. هيدرانجيا بيضاء مع ورد لافندر.',
                'slug' => 'celestial-promise-bouquet',
                'price' => 44.000,
                'sale_price' => null,
                'image' => 'products/weddings/celestial-promise-bouquet.jpg',
                'images' => ['products/weddings/celestial-promise-bouquet-2.jpg'],
                'sku' => 'WED-004',
                'stock' => 12,
                'rating' => 4.7,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $weddings->id,
                'name_en' => 'Royal Union Fleur',
                'name_ar' => 'زهرة الاتحاد الملكي',
                'description_en' => 'A luxurious handcrafted bouquet designed for unforgettable wedding moments. Imported Premium Roses with Pearl Wrap and Eucalyptus.',
                'description_ar' => 'باقة فاخرة مصنوعة يدوياً مصممة لللحظات زفاف التي لا تُنسى. ورد مستورد فاخر بلفة لؤلؤية وأوكالبتوس.',
                'slug' => 'royal-union-fleur',
                'price' => 55.000,
                'sale_price' => null,
                'image' => 'products/weddings/royal-union-fleur.jpg',
                'images' => ['products/weddings/royal-union-fleur-2.jpg'],
                'sku' => 'WED-005',
                'stock' => 5,
                'rating' => 5.0,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 03 — BIRTHDAY
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $birthday->id,
                'name_en' => 'Sunset Confetti Bloom',
                'name_ar' => 'إزهار الكونفيتي الغروبي',
                'description_en' => 'A vibrant and cheerful bouquet bursting with birthday energy and happiness. Orange Roses, Yellow Tulips, and White Daisies.',
                'description_ar' => 'باقة نابضة بالحياة ومبهجة تنفطر بطاقة عيد الميلاد والسعادة. ورد برتقالي مع تول أصفر وديزي أبيض.',
                'slug' => 'sunset-confetti-bloom',
                'price' => 21.000,
                'sale_price' => null,
                'image' => 'products/birthday/sunset-confetti-bloom.jpg',
                'images' => [],
                'sku' => 'BDY-001',
                'stock' => 40,
                'rating' => 4.3,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $birthday->id,
                'name_en' => 'Velvet Wish Petals',
                'name_ar' => 'بتلات الأمنية المخملية',
                'description_en' => 'A charming arrangement filled with soft colors and celebratory warmth. Pink Carnations with Purple Chrysanthemums.',
                'description_ar' => 'ترتيب ساحر مليء بالألوان الناعمة والدفء الاحتفالي. قرنفل وردي مع أقحوان بنفسجي.',
                'slug' => 'velvet-wish-petals',
                'price' => 20.000,
                'sale_price' => null,
                'image' => 'products/birthday/velvet-wish-petals.jpg',
                'images' => [],
                'sku' => 'BDY-002',
                'stock' => 45,
                'rating' => 4.1,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $birthday->id,
                'name_en' => 'Golden Spark Bouquet',
                'name_ar' => 'باقة الشرارة الذهبية',
                'description_en' => 'A bright and energetic bouquet symbolizing positivity and joyful memories. Sunflowers with Red Roses and Baby\'s Breath.',
                'description_ar' => 'باقة مشرقة وحيوية ترمز للإيجابية والذكريات المبهجة. زهرة الشمس مع ورد أحمر وأنفاس الطفل.',
                'slug' => 'golden-spark-bouquet',
                'price' => 25.000,
                'sale_price' => null,
                'image' => 'products/birthday/golden-spark-bouquet.jpg',
                'images' => ['products/birthday/golden-spark-bouquet-2.jpg'],
                'sku' => 'BDY-003',
                'stock' => 35,
                'rating' => 4.5,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $birthday->id,
                'name_en' => 'Lavender Frost Garden',
                'name_ar' => 'حديقة الصقيع اللافندر',
                'description_en' => 'A calm yet luxurious floral arrangement with a modern elegant aesthetic. Lavender Roses with White Lilies.',
                'description_ar' => 'ترتيب زهور هادئ وفاخر بجمالية أنيقة وعصرية. ورد لافندر مع زنابق بيضاء.',
                'slug' => 'lavender-frost-garden',
                'price' => 27.000,
                'sale_price' => null,
                'image' => 'products/birthday/lavender-frost-garden.jpg',
                'images' => [],
                'sku' => 'BDY-004',
                'stock' => 25,
                'rating' => 4.4,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $birthday->id,
                'name_en' => 'Cherry Glow Ensemble',
                'name_ar' => 'مجموعة توهج الكرز',
                'description_en' => 'A playful and stylish bouquet designed for modern birthday celebrations. Red Tulips with Peach Roses and Eucalyptus.',
                'description_ar' => 'باقة مرحة وأنيقة مصممة لاحتفالات عيد الميلاد العصرية. تول أحمر مع ورد خوخي وأوكالبتوس.',
                'slug' => 'cherry-glow-ensemble',
                'price' => 23.000,
                'sale_price' => 19.000,
                'image' => 'products/birthday/cherry-glow-ensemble.jpg',
                'images' => [],
                'sku' => 'BDY-005',
                'stock' => 30,
                'rating' => 4.2,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 04 — ANNIVERSARY
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $anniversary->id,
                'name_en' => 'Eternal Flame Roses',
                'name_ar' => 'ورود اللهب الأبدي',
                'description_en' => 'A passionate arrangement symbolizing enduring love and unforgettable memories. Deep Red Roses with Silver Leaf Accents.',
                'description_ar' => 'ترتيب عاطفي يرمز للحب الدائم والذكريات التي لا تُنسى. ورد أحمر عميق مع لمسات أوراق فضية.',
                'slug' => 'eternal-flame-roses',
                'price' => 38.000,
                'sale_price' => null,
                'image' => 'products/anniversary/eternal-flame-roses.jpg',
                'images' => ['products/anniversary/eternal-flame-roses-2.jpg'],
                'sku' => 'ANN-001',
                'stock' => 20,
                'rating' => 4.8,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $anniversary->id,
                'name_en' => 'Champagne Love Garden',
                'name_ar' => 'حديقة حب الشمبانيا',
                'description_en' => 'A refined bouquet inspired by elegant romance and timeless relationships. Champagne Roses with White Tulips.',
                'description_ar' => 'باقة راقية مستوحاة من الرومانسية الأنيقة والعلاقات الخالدة. ورد شمبانيا مع تول أبيض.',
                'slug' => 'champagne-love-garden',
                'price' => 34.000,
                'sale_price' => null,
                'image' => 'products/anniversary/champagne-love-garden.jpg',
                'images' => [],
                'sku' => 'ANN-002',
                'stock' => 18,
                'rating' => 4.6,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $anniversary->id,
                'name_en' => 'Velvet Promise Bouquet',
                'name_ar' => 'باقة الوعد المخملي',
                'description_en' => 'A luxurious floral mix expressing loyalty, affection, and appreciation. Crimson Carnations with Ivory Roses.',
                'description_ar' => 'مزيج زهور فاخر يعبر عن الولاء والمودة والتقدير. قرنفل قرمزي مع ورد عاجي.',
                'slug' => 'velvet-promise-bouquet',
                'price' => 31.000,
                'sale_price' => null,
                'image' => 'products/anniversary/velvet-promise-bouquet.jpg',
                'images' => [],
                'sku' => 'ANN-003',
                'stock' => 22,
                'rating' => 4.4,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $anniversary->id,
                'name_en' => 'Moonstone Romance Bloom',
                'name_ar' => 'إزهار رومانسية حجر القمر',
                'description_en' => 'A graceful arrangement with soft romantic tones and premium floral styling. White Orchids with Pink Lilies.',
                'description_ar' => 'ترتيب رشيق بدرجات رومانسية ناعمة وتصميم زهري فاخر. أوركيد أبيض مع زنابق وردية.',
                'slug' => 'moonstone-romance-bloom',
                'price' => 43.000,
                'sale_price' => null,
                'image' => 'products/anniversary/moonstone-romance-bloom.jpg',
                'images' => ['products/anniversary/moonstone-romance-bloom-2.jpg'],
                'sku' => 'ANN-004',
                'stock' => 10,
                'rating' => 4.7,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $anniversary->id,
                'name_en' => 'Sapphire Heart Ensemble',
                'name_ar' => 'مجموعة قلب الياقوت الأزرق',
                'description_en' => 'A rare and elegant bouquet designed to represent trust and deep emotional connection. Blue Hydrangeas with White Roses.',
                'description_ar' => 'باقة نادرة وأنيقة مصممة لتمثيل الثقة والارتباط العاطفي العميق. هيدرانجيا زرقاء مع ورد أبيض.',
                'slug' => 'sapphire-heart-ensemble',
                'price' => 40.000,
                'sale_price' => null,
                'image' => 'products/anniversary/sapphire-heart-ensemble.jpg',
                'images' => [],
                'sku' => 'ANN-005',
                'stock' => 12,
                'rating' => 4.9,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 05 — GRADUATION
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $graduation->id,
                'name_en' => 'Golden Triumph Bouquet',
                'name_ar' => 'باقة الانتصار الذهبي',
                'description_en' => 'A bright arrangement symbolizing success, confidence, and future achievements. Sunflowers with White Roses and Eucalyptus.',
                'description_ar' => 'ترتيب مشرق يرمز للنجاح والثقة والإنجازات المستقبلية. زهرة الشمس مع ورد أبيض وأوكالبتوس.',
                'slug' => 'golden-triumph-bouquet',
                'price' => 24.000,
                'sale_price' => null,
                'image' => 'products/graduation/golden-triumph-bouquet.jpg',
                'images' => [],
                'sku' => 'GRD-001',
                'stock' => 35,
                'rating' => 4.5,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $graduation->id,
                'name_en' => 'Scholar\'s Bloom Basket',
                'name_ar' => 'سلة إزهار العالم',
                'description_en' => 'A youthful and uplifting floral basket designed to celebrate academic milestones. Yellow Tulips with Purple Carnations.',
                'description_ar' => 'سلة زهور شبابية ومبهجة مصممة للاحتفال بالإنجازات الأكاديمية. تول أصفر مع قرنفل بنفسجي.',
                'slug' => 'scholars-bloom-basket',
                'price' => 22.000,
                'sale_price' => null,
                'image' => 'products/graduation/scholars-bloom-basket.jpg',
                'images' => [],
                'sku' => 'GRD-002',
                'stock' => 40,
                'rating' => 4.2,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $graduation->id,
                'name_en' => 'Victory Petal Ensemble',
                'name_ar' => 'مجموعة بتلات النصر',
                'description_en' => 'A vibrant bouquet representing ambition, courage, and fresh beginnings. Orange Lilies with Cream Roses.',
                'description_ar' => 'باقة نابضة تمثل الطموح والشجاعة والبدايات الجديدة. زنابق برتقالية مع ورد كريمي.',
                'slug' => 'victory-petal-ensemble',
                'price' => 26.000,
                'sale_price' => null,
                'image' => 'products/graduation/victory-petal-ensemble.jpg',
                'images' => ['products/graduation/victory-petal-ensemble-2.jpg'],
                'sku' => 'GRD-003',
                'stock' => 28,
                'rating' => 4.4,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $graduation->id,
                'name_en' => 'Future Horizon Garden',
                'name_ar' => 'حديقة أفق المستقبل',
                'description_en' => 'A modern arrangement symbolizing dreams, vision, and exciting opportunities ahead. White Hydrangeas with Blue Roses.',
                'description_ar' => 'ترتيب عصري يرمز للأحلام والرؤية والفرص المثيرة القادمة. هيدرانجيا بيضاء مع ورد أزرق.',
                'slug' => 'future-horizon-garden',
                'price' => 32.000,
                'sale_price' => null,
                'image' => 'products/graduation/future-horizon-garden.jpg',
                'images' => [],
                'sku' => 'GRD-004',
                'stock' => 15,
                'rating' => 4.6,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $graduation->id,
                'name_en' => 'Prestige Laurel Bloom',
                'name_ar' => 'إزهار الغار الفاخر',
                'description_en' => 'A luxurious floral arrangement inspired by excellence and prestige. Green Orchids with Gold-Wrapped Roses.',
                'description_ar' => 'ترتيب زهور فاخر مستوحى من التميز والبريستيج. أوركيد أخضر مع ورد ملفوف بالذهب.',
                'slug' => 'prestige-laurel-bloom',
                'price' => 36.000,
                'sale_price' => null,
                'image' => 'products/graduation/prestige-laurel-bloom.jpg',
                'images' => ['products/graduation/prestige-laurel-bloom-2.jpg'],
                'sku' => 'GRD-005',
                'stock' => 8,
                'rating' => 4.8,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 06 — MOTHER'S DAY
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $mothersDay->id,
                'name_en' => 'Velvet Embrace Bouquet',
                'name_ar' => 'باقة العناق المخملية',
                'description_en' => 'A warm and affectionate arrangement celebrating a mother\'s unconditional love. Pink Roses with White Carnations.',
                'description_ar' => 'ترتيب دافئ ومحتفل بحب الأم غير المشروط. ورد وردي مع قرنفل أبيض.',
                'slug' => 'velvet-embrace-bouquet',
                'price' => 28.000,
                'sale_price' => null,
                'image' => 'products/mothers-day/velvet-embrace-bouquet.jpg',
                'images' => [],
                'sku' => 'MOM-001',
                'stock' => 30,
                'rating' => 4.6,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $mothersDay->id,
                'name_en' => 'Pearl Garden Grace',
                'name_ar' => 'أناقة حديقة اللؤلؤ',
                'description_en' => 'A soft and elegant bouquet symbolizing purity, care, and gratitude. White Lilies with Peach Roses.',
                'description_ar' => 'باقة ناعمة وأنيقة ترمز للنقاء والرعاية والامتنان. زنابق بيضاء مع ورد خوخي.',
                'slug' => 'pearl-garden-grace',
                'price' => 30.000,
                'sale_price' => null,
                'image' => 'products/mothers-day/pearl-garden-grace.jpg',
                'images' => ['products/mothers-day/pearl-garden-grace-2.jpg'],
                'sku' => 'MOM-002',
                'stock' => 22,
                'rating' => 4.5,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $mothersDay->id,
                'name_en' => 'Blush Harmony Bloom',
                'name_ar' => 'إزهار الانسجام الوردي',
                'description_en' => 'A delicate arrangement designed to express warmth, tenderness, and admiration. Pink Tulips with Baby\'s Breath.',
                'description_ar' => 'ترتيب رقيق مصمم للتعبير عن الدفء والرقة والإعجاب. تول وردي مع أنفاس الطفل.',
                'slug' => 'blush-harmony-bloom',
                'price' => 24.000,
                'sale_price' => null,
                'image' => 'products/mothers-day/blush-harmony-bloom.jpg',
                'images' => [],
                'sku' => 'MOM-003',
                'stock' => 35,
                'rating' => 4.3,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $mothersDay->id,
                'name_en' => 'Golden Motherlight Basket',
                'name_ar' => 'سلة نور الأم الذهبية',
                'description_en' => 'A cheerful floral basket representing strength, positivity, and nurturing love. Sunflowers with Cream Carnations.',
                'description_ar' => 'سلة زهور مبهجة تمثل القوة والإيجابية والحب الحنون. زهرة الشمس مع قرنفل كريمي.',
                'slug' => 'golden-motherlight-basket',
                'price' => 26.000,
                'sale_price' => 22.000,
                'image' => 'products/mothers-day/golden-motherlight-basket.jpg',
                'images' => [],
                'sku' => 'MOM-004',
                'stock' => 28,
                'rating' => 4.4,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $mothersDay->id,
                'name_en' => 'Queen\'s Affection Ensemble',
                'name_ar' => 'مجموعة عاطفة الملكة',
                'description_en' => 'A luxurious bouquet made to honor mothers with elegance and beauty. Premium Red and Pink Roses with Eucalyptus.',
                'description_ar' => 'باقة فاخرة مصنوعة لتكريم الأمهات بالأناقة والجمال. ورد أحمر ووردي فاخر مع أوكالبتوس.',
                'slug' => 'queens-affection-ensemble',
                'price' => 39.000,
                'sale_price' => null,
                'image' => 'products/mothers-day/queens-affection-ensemble.jpg',
                'images' => ['products/mothers-day/queens-affection-ensemble-2.jpg'],
                'sku' => 'MOM-005',
                'stock' => 10,
                'rating' => 4.9,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 07 — LOVE & ROMANCE
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $loveRomance->id,
                'name_en' => 'Crimson Desire Bouquet',
                'name_ar' => 'باقة الرغبة القرمزية',
                'description_en' => 'A bold romantic bouquet designed to express passion and deep affection. Red Roses with Black Wrap and Silver Leaves.',
                'description_ar' => 'باقة رومانسية جريئة مصممة للتعبير عن الشغف والمودة العميقة. ورد أحمر بلفة سوداء وأوراق فضية.',
                'slug' => 'crimson-desire-bouquet',
                'price' => 35.000,
                'sale_price' => null,
                'image' => 'products/love-romance/crimson-desire-bouquet.jpg',
                'images' => ['products/love-romance/crimson-desire-bouquet-2.jpg'],
                'sku' => 'LVR-001',
                'stock' => 25,
                'rating' => 4.7,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $loveRomance->id,
                'name_en' => 'Midnight Serenade Bloom',
                'name_ar' => 'إزهار سيريناد منتصف الليل',
                'description_en' => 'A mysterious and luxurious arrangement inspired by elegant romance. Dark Burgundy Roses with White Orchids.',
                'description_ar' => 'ترتيب غامض وفاخر مستوحى من الرومانسية الأنيقة. ورد بورغندي داكن مع أوركيد أبيض.',
                'slug' => 'midnight-serenade-bloom',
                'price' => 41.000,
                'sale_price' => null,
                'image' => 'products/love-romance/midnight-serenade-bloom.jpg',
                'images' => [],
                'sku' => 'LVR-002',
                'stock' => 12,
                'rating' => 4.8,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $loveRomance->id,
                'name_en' => 'Blushing Heart Garden',
                'name_ar' => 'حديقة القلب المتهادي',
                'description_en' => 'A sweet and charming bouquet filled with warmth and soft romantic energy. Pink Tulips with Peach Carnations.',
                'description_ar' => 'باقة حلوة وساحرة مليئة بالدفء والطاقة الرومانسية الناعمة. تول وردي مع قرنفل خوخي.',
                'slug' => 'blushing-heart-garden',
                'price' => 27.000,
                'sale_price' => null,
                'image' => 'products/love-romance/blushing-heart-garden.jpg',
                'images' => [],
                'sku' => 'LVR-003',
                'stock' => 30,
                'rating' => 4.4,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $loveRomance->id,
                'name_en' => 'Eternal Kiss Ensemble',
                'name_ar' => 'مجموعة القبلة الأبدية',
                'description_en' => 'A graceful arrangement symbolizing commitment, trust, and everlasting love. Red Tulips with White Roses.',
                'description_ar' => 'ترتيب رشيق يرمز للالتزام والثقة والحب الأبدي. تول أحمر مع ورد أبيض.',
                'slug' => 'eternal-kiss-ensemble',
                'price' => 33.000,
                'sale_price' => null,
                'image' => 'products/love-romance/eternal-kiss-ensemble.jpg',
                'images' => ['products/love-romance/eternal-kiss-ensemble-2.jpg'],
                'sku' => 'LVR-004',
                'stock' => 18,
                'rating' => 4.6,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $loveRomance->id,
                'name_en' => 'Rosewood Passion Fleur',
                'name_ar' => 'زهرة شغف خشب الورد',
                'description_en' => 'A luxurious handcrafted bouquet designed for unforgettable romantic gestures. Premium Imported Roses with Baby\'s Breath.',
                'description_ar' => 'باقة فاخرة مصنوعة يدوياً مصممة للإيماءات الرومانسية التي لا تُنسى. ورد مستورد فاخر مع أنفاس الطفل.',
                'slug' => 'rosewood-passion-fleur',
                'price' => 49.000,
                'sale_price' => null,
                'image' => 'products/love-romance/rosewood-passion-fleur.jpg',
                'images' => ['products/love-romance/rosewood-passion-fleur-2.jpg', 'products/love-romance/rosewood-passion-fleur-3.jpg'],
                'sku' => 'LVR-005',
                'stock' => 6,
                'rating' => 5.0,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],

            // ═══════════════════════════════════════════════════════
            // 08 — SYMPATHY
            // ═══════════════════════════════════════════════════════
            [
                'category_id' => $sympathy->id,
                'name_en' => 'Silent Ivory Grace',
                'name_ar' => 'نعمة العاج الصامتة',
                'description_en' => 'A peaceful arrangement expressing comfort, remembrance, and sincere condolences. White Lilies with White Roses.',
                'description_ar' => 'ترتيب هادئ يعبر عن المواساة والذكرى والتعازي الصادقة. زنابق بيضاء مع ورد أبيض.',
                'slug' => 'silent-ivory-grace',
                'price' => 31.000,
                'sale_price' => null,
                'image' => 'products/sympathy/silent-ivory-grace.jpg',
                'images' => [],
                'sku' => 'SYMP-001',
                'stock' => 20,
                'rating' => 4.5,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $sympathy->id,
                'name_en' => 'Heavenly Calm Bouquet',
                'name_ar' => 'باقة الهدوء السماوي',
                'description_en' => 'A serene floral arrangement symbolizing peace, purity, and eternal rest. White Orchids with Silver Leaves.',
                'description_ar' => 'ترتيب زهور هادئ يرمز للسلام والنقاء والراحة الأبدية. أوركيد أبيض مع أوراق فضية.',
                'slug' => 'heavenly-calm-bouquet',
                'price' => 36.000,
                'sale_price' => null,
                'image' => 'products/sympathy/heavenly-calm-bouquet.jpg',
                'images' => ['products/sympathy/heavenly-calm-bouquet-2.jpg'],
                'sku' => 'SYMP-002',
                'stock' => 15,
                'rating' => 4.7,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $sympathy->id,
                'name_en' => 'Gentle Farewell Bloom',
                'name_ar' => 'إزهار الوداع الرقيق',
                'description_en' => 'A soft and comforting bouquet created to honor cherished memories. White Carnations with Baby\'s Breath.',
                'description_ar' => 'باقة ناعمة ومواسية مصممة لتكريم الذكريات العزيزة. قرنفل أبيض مع أنفاس الطفل.',
                'slug' => 'gentle-farewell-bloom',
                'price' => 25.000,
                'sale_price' => null,
                'image' => 'products/sympathy/gentle-farewell-bloom.jpg',
                'images' => [],
                'sku' => 'SYMP-003',
                'stock' => 25,
                'rating' => 4.3,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $sympathy->id,
                'name_en' => 'Eternal Peace Garden',
                'name_ar' => 'حديقة السلام الأبدي',
                'description_en' => 'A graceful floral display designed to bring comfort during difficult moments. White Hydrangeas with Ivory Roses.',
                'description_ar' => 'عرض زهور رشيق مصمم لجلب المواساة في اللحظات الصعبة. هيدرانجيا بيضاء مع ورد عاجي.',
                'slug' => 'eternal-peace-garden',
                'price' => 34.000,
                'sale_price' => null,
                'image' => 'products/sympathy/eternal-peace-garden.jpg',
                'images' => [],
                'sku' => 'SYMP-004',
                'stock' => 15,
                'rating' => 4.6,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $sympathy->id,
                'name_en' => 'Dove Serenity Ensemble',
                'name_ar' => 'مجموعة هدوء الحمامة',
                'description_en' => 'An elegant arrangement symbolizing hope, compassion, and heartfelt support. Cream Roses with White Tulips and Eucalyptus.',
                'description_ar' => 'ترتيب أنيق يرمز للأمل والتعاطف والدعم الصادق. ورد كريمي مع تول أبيض وأوكالبتوس.',
                'slug' => 'dove-serenity-ensemble',
                'price' => 29.000,
                'sale_price' => null,
                'image' => 'products/sympathy/dove-serenity-ensemble.jpg',
                'images' => ['products/sympathy/dove-serenity-ensemble-2.jpg'],
                'sku' => 'SYMP-005',
                'stock' => 20,
                'rating' => 4.4,
                'is_featured' => false,
                'is_best_seller' => false,
                'is_new' => false,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
